In [1]:
using SymPy

┌ Info: Installing sympy via the Conda sympy package...
└ @ PyCall C:\Users\gmanu\.julia\packages\PyCall\1gn3u\src\PyCall.jl:719
┌ Info: Running `conda install -y sympy` in root environment
└ @ Conda C:\Users\gmanu\.julia\packages\Conda\zReqD\src\Conda.jl:181


Retrieving notices: done
Channels:
 - defaults
 - conda-forge
Platform: win-64
Solving environment: ...working... done




==> WARNING: A newer version of conda exists. <==
    current version: 24.11.3
    latest version: 25.1.1

Please update conda by running

    $ conda update -n base -c conda-forge conda





## Package Plan ##

  environment location: C:\Users\gmanu\.julia\conda\3\x86_64

  added / updated specs:
    - sympy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gmp-6.3.0                  |       h537511b_0         330 KB
    gmpy2-2.2.1                |  py312h827c3e9_0         205 KB
    mpc-1.3.1                  |       h827c3e9_0          85 KB
    mpfr-4.2.1                 |       h56c3642_0         266 KB
    mpmath-1.3.0               |  py312haa95532_0         989 KB
    sympy-1.13.3               |  py312haa95532_1        15.0 MB
    ------------------------------------------------------------
                                           Total:        16.8 MB

The following NEW packages will be INSTALLED:

  gmp                pkgs/main/win-64::gmp-6.3.0-h537511b_0 
  gmpy2              pkgs/main/win-64::gmpy2-2.2.1-py312h827c3e9_0 
  mpc                pkgs/main/win-64

In [2]:
using LinearAlgebra

In [3]:
A = [1 2 3; 4 1 6; 7 8 1]

3×3 Matrix{Int64}:
 1  2  3
 4  1  6
 7  8  1

In [6]:
tr(A)


3

In [8]:
det(A)

104.0

In [7]:
inv(A)


3×3 Matrix{Float64}:
 -0.451923   0.211538    0.0865385
  0.365385  -0.192308    0.0576923
  0.240385   0.0576923  -0.0673077

MATRICES

In [11]:
sympy.Matrix([[1, -1], [3, 4], [0, 2]])

3×2 Matrix{Sym{PyCall.PyObject}}:
 1  -1
 3   4
 0   2

También se puede reescribir como

In [12]:
Sym[1 -1; 3 4 ; 0 2]

3×2 Matrix{Sym}:
 1  -1
 3   4
 0   2

In [13]:
[Sym(1) -1; 3 4 ; 0 2]

3×2 Matrix{Sym{PyCall.PyObject}}:
 1  -1
 3   4
 0   2

In [17]:
[Sym(1) Sym(-1); 3 4 ; 0 2]

3×2 Matrix{Sym{PyCall.PyObject}}:
 1  -1
 3   4
 0   2

In [15]:
sympy.Matrix([1, 2, 3])

3×1 Matrix{Sym{PyCall.PyObject}}:
 1
 2
 3

In [16]:
Sym[1,2,3]

3-element Vector{Sym}:
 1
 2
 3

Operaciones de matrices


In [22]:
M = Sym[1 2 3; 3 2 1]

2×3 Matrix{Sym}:
 1  2  3
 3  2  1

In [23]:
N = Sym[0, 1, 1]

3-element Vector{Sym}:
 0
 1
 1

In [24]:
M * N 

2-element Vector{Sym}:
 5
 3

Shape para obtener la forma de una matriz

In [45]:
 B = Sym[1 2 3; -2 0 4]

2×3 Matrix{Sym}:
  1  2  3
 -2  0  4

In [27]:
B.shape

(2, 3)

In [28]:
size(B)

(2, 3)

Filas y columnas 

In [31]:
B.row(0)

1×3 Matrix{Sym{PyCall.PyObject}}:
 1  2  3

In [32]:
B.row(1)

1×3 Matrix{Sym{PyCall.PyObject}}:
 -2  0  4

In [33]:
B.col(-1)

2×1 Matrix{Sym{PyCall.PyObject}}:
 3
 4

In [34]:
B.col(0)

2×1 Matrix{Sym{PyCall.PyObject}}:
  1
 -2

In [35]:
B.col(1)

2×1 Matrix{Sym{PyCall.PyObject}}:
 2
 0

In [36]:
B.col(2)

2×1 Matrix{Sym{PyCall.PyObject}}:
 3
 4

In [37]:
B[1,:]

3-element Vector{Sym}:
 1
 2
 3

In [39]:
B[2,:]

3-element Vector{Sym}:
 -2
  0
  4

In [40]:
B[:,1]

2-element Vector{Sym}:
  1
 -2

In [38]:
B[:,end]

2-element Vector{Sym}:
 3
 4

Borrando y adjuntato filas y columnas

In [61]:
B = sympy.Matrix([[1, 2, 3], [-2, 0, 4]])

2×3 Matrix{Sym{PyCall.PyObject}}:
  1  2  3
 -2  0  4

In [62]:
B = sympy.ImmutableMatrix([[1, 2, 3], [-2, 0, 4]])

[1   2  3]
[        ]
[-2  0  4]

In [63]:
B.col_del(0)

[2  3]
[    ]
[0  4]

In [66]:
B.row_del(1)

[1  2  3]

In [67]:
@syms x

(x,)

In [68]:
sympy.ImmutableMatrix([x 1;  1  x])

[x  1]
[    ]
[1  x]

In [69]:
M = sympy.ImmutableMatrix([2 3])

[2  3]

In [70]:
M = M.row_insert(1, Sym[0 4])

[2  3]
[    ]
[0  4]

In [71]:
M = M.col_insert(0, Sym[1, -2])

[1   2  3]
[        ]
[-2  0  4]

Métodos básicos

In [73]:
M = sympy.Matrix([[1, 3], [-2, 3]])

2×2 Matrix{Sym{PyCall.PyObject}}:
  1  3
 -2  3

In [74]:
N = sympy.Matrix([[0, 3], [0, 7]])

2×2 Matrix{Sym{PyCall.PyObject}}:
 0  3
 0  7

In [75]:
M+N

2×2 Matrix{Sym{PyCall.PyObject}}:
  1   6
 -2  10

In [76]:
M-N

2×2 Matrix{Sym{PyCall.PyObject}}:
  1   0
 -2  -4

In [77]:
M*N

2×2 Matrix{Sym{PyCall.PyObject}}:
 0  24
 0  15

In [78]:
3*M

2×2 Matrix{Sym{PyCall.PyObject}}:
  3  9
 -6  9

In [82]:
M*M

2×2 Matrix{Sym{PyCall.PyObject}}:
 -5  12
 -8   3

In [84]:
M^2

2×2 Matrix{Sym{PyCall.PyObject}}:
 -5  12
 -8   3

In [85]:
M^-1

2×2 Matrix{Sym{PyCall.PyObject}}:
 1/3  -1/3
 2/9   1/9

In [86]:
N^2

2×2 Matrix{Sym{PyCall.PyObject}}:
 0  21
 0  49

In [88]:
M = sympy.ImmutableMatrix([1 3; -2 3])

[1   3]
[     ]
[-2  3]

In [89]:
M1 = sympy.ImmutableMatrix([0 3; 0 7])

[0  3]
[    ]
[0  7]

In [90]:
M + M1

[1   6 ]
[      ]
[-2  10]

In [91]:
M*M1

[0  24]
[     ]
[0  15]

Tranpuesta

In [93]:
M = sympy.Matrix([[1, 2, 3], [4, 5, 6]])

2×3 Matrix{Sym{PyCall.PyObject}}:
 1  2  3
 4  5  6

In [94]:
M.T

3×2 Matrix{Sym{PyCall.PyObject}}:
 1  4
 2  5
 3  6

In [95]:
M1.T

[0  0]
[    ]
[3  7]

Construir matrices

In [100]:
sympy.eye(3)

3×3 Matrix{Sym{PyCall.PyObject}}:
 1  0  0
 0  1  0
 0  0  1

In [101]:
sympy.eye(4)

4×4 Matrix{Sym{PyCall.PyObject}}:
 1  0  0  0
 0  1  0  0
 0  0  1  0
 0  0  0  1

In [102]:
5/2*sympy.eye(3)

3×3 Matrix{Sym{PyCall.PyObject}}:
 2.50000000000000                 0                 0
                0  2.50000000000000                 0
                0                 0  2.50000000000000

In [103]:
sympy.zeros(2, 3)

2×3 Matrix{Sym{PyCall.PyObject}}:
 0  0  0
 0  0  0

In [105]:
sympy.zeros(Sym(2), 3)

2×3 Matrix{Sym{PyCall.PyObject}}:
 0  0  0
 0  0  0

In [108]:
ones(3,2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [110]:
sympy.diag(1, 2, 3)

3×3 Matrix{Sym{PyCall.PyObject}}:
 1  0  0
 0  2  0
 0  0  3

In [111]:
sympy.diag(-1, sympy.ones(2, 2), sympy.Matrix([5, 7, 5]))

6×4 Matrix{Sym{PyCall.PyObject}}:
 -1  0  0  0
  0  1  1  0
  0  1  1  0
  0  0  0  5
  0  0  0  7
  0  0  0  5

In [112]:
diagm(0 => Sym[1,2,3])

3×3 Matrix{Sym{PyCall.PyObject}}:
 1  0  0
 0  2  0
 0  0  3

Métodos avanzados

In [113]:
M = sympy.Matrix([[1, 0, 1], [2, -1, 3], [4, 3, 2]])

3×3 Matrix{Sym{PyCall.PyObject}}:
 1   0  1
 2  -1  3
 4   3  2

In [114]:
M.det()

-1

In [115]:
det(M)

-1

In [116]:
@syms x

(x,)

In [117]:
A = Sym[x 1; 1 x]

2×2 Matrix{Sym}:
 x  1
 1  x

In [118]:
det(A)

 2    
x  - 1

In [119]:
A.det()

 2    
x  - 1

In [122]:
out = lu(A)

LU{Sym{PyCall.PyObject}, Matrix{Sym{PyCall.PyObject}}, Vector{Int64}}
L factor:
2×2 Matrix{Sym{PyCall.PyObject}}:
   1  0
 1/x  1
U factor:
2×2 Matrix{Sym{PyCall.PyObject}}:
 x        1
 0  x - 1/x

In [123]:
prod(diag(out.L)) * prod(diag(out.U))

  /    1\
x*|x - -|
  \    x/

RREF

In [124]:
M = sympy.Matrix([[1, 0, 1, 3], [2, 3, 4, 7], [-1, -3, -3, -4]])

3×4 Matrix{Sym{PyCall.PyObject}}:
  1   0   1   3
  2   3   4   7
 -1  -3  -3  -4

In [125]:
M.rref()

(Sym{PyCall.PyObject}[1 0 1 3; 0 1 2/3 1/3; 0 0 0 0], (0, 1))

Nullspace

In [130]:
M = Sym[1 2 3 0 0; 4 10 0 0 1]

2×5 Matrix{Sym}:
 1   2  3  0  0
 4  10  0  0  1

In [133]:
M.nullspace()

3-element Vector{Matrix{Sym{PyCall.PyObject}}}:
 [-15; 6; … ; 0; 0;;]
 [0; 0; … ; 1; 0;;]
 [1; -1/2; … ; 0; 1;;]

Columnspace

In [134]:
M = Sym[1 2 2; 2 1 3; 3 1 4]

3×3 Matrix{Sym}:
 1  2  2
 2  1  3
 3  1  4

In [135]:
M.columnspace()

3-element Vector{Matrix{Sym{PyCall.PyObject}}}:
 [1; 2; 3;;]
 [2; 1; 1;;]
 [2; 3; 4;;]

Eigenvalores, eigenvectores y diagonalización

In [136]:
M = Sym[3 -2  4 -2; 5  3 -3 -2; 5 -2  2 -2; 5 -2 -3  3]

4×4 Matrix{Sym}:
 3  -2   4  -2
 5   3  -3  -2
 5  -2   2  -2
 5  -2  -3   3

In [137]:
M.eigenvals()

Dict{Sym{PyCall.PyObject}, Sym{PyCall.PyObject}} with 3 entries:
  3  => 1
  5  => 2
  -2 => 1

In [138]:
M.eigenvects()

3-element Vector{Tuple{Sym{PyCall.PyObject}, Sym{PyCall.PyObject}, Vector{Matrix{Sym{PyCall.PyObject}}}}}:
 (-2, 1, [[0; 1; 1; 1;;]])
 (3, 1, [[1; 1; 1; 1;;]])
 (5, 2, [[1; 1; 1; 0;;], [0; -1; 0; 1;;]])

In [139]:
eigvecs(M)

4×4 Matrix{Sym{PyCall.PyObject}}:
 0  1  1   0
 1  1  1  -1
 1  1  1   0
 1  1  0   1

In [140]:
P, D = M.diagonalize()

(Sym{PyCall.PyObject}[0 1 1 0; 1 1 1 -1; 1 1 1 0; 1 1 0 1], Sym{PyCall.PyObject}[-2 0 0 0; 0 3 0 0; 0 0 5 0; 0 0 0 5])

In [141]:
P

4×4 Matrix{Sym{PyCall.PyObject}}:
 0  1  1   0
 1  1  1  -1
 1  1  1   0
 1  1  0   1

In [142]:
D

4×4 Matrix{Sym{PyCall.PyObject}}:
 -2  0  0  0
  0  3  0  0
  0  0  5  0
  0  0  0  5

In [143]:
P^-1

4×4 Matrix{Sym{PyCall.PyObject}}:
 -1   0   1   0
  1   1  -2   1
  0  -1   2  -1
  0  -1   1   0

In [144]:
P*D*P^-1

4×4 Matrix{Sym{PyCall.PyObject}}:
 3  -2   4  -2
 5   3  -3  -2
 5  -2   2  -2
 5  -2  -3   3

In [145]:
P*D*P^-1 == M

true

Polinomio característico

In [147]:
@syms lambda

(lambda,)

In [148]:
p = M.charpoly(lambda)

PurePoly(lambda^4 - 11*lambda^3 + 29*lambda^2 + 35*lambda - 150, lambda, do >

> main='ZZ')

In [149]:
factor(p) |>  string

"PurePoly(lambda^4 - 11*lambda^3 + 29*lambda^2 + 35*lambda - 150, lambda, domain='ZZ')"

Zero testing

In [151]:
q = sympy.Symbol("q", positive = true)

q

In [152]:
m = Sym[-2*cosh(q/3) exp(-q) 1; exp(q) -2*cosh(q/3) 1; 1 1 -2*cosh(q/3)]

3×3 Matrix{Sym}:
 -2*cosh(q/3)       exp(-q)             1
       exp(q)  -2*cosh(q/3)             1
            1             1  -2*cosh(q/3)

In [153]:
m.nullspace()

1-element Vector{Matrix{Sym{PyCall.PyObject}}}:
 [-(-2*exp(q)*cosh(q/3) - 4*cosh(q/3)^2 - 1 - 2*exp(-q)*cosh(q/3))/(4*exp(q)*cosh(q/3)^2 + 4*cosh(q/3) + exp(-q)); -(1 - 4*cosh(q/3)^2)/(2*cosh(q/3) + exp(-q)); 1;;]